/* eslint-disable no-unused-vars */
export const STATUS_CODE = {
  '200': 200,
  '201': 201,
  '400': 400,
  '401': 401,
  '500': 500,
  '403': 403,
  '404': 404,
  '406': 406,
} as const;
export enum ROUTES {
  USER = '/user',
  AUTH = '/auth',
  CREDIT = '/credit',
  EMPLOYEE = '/employee',
  CUSTOMER_FILE = '/customer-file',
  SIGNED_URL = '/signed-url',
  IFSC = '/ifsc/:ifsc',
  OCR = '/ocr',
  LOGIN = '/login',
  LOGOUT = '/logout',
  FORGOT_PASSWORD = '/forgot-password',
  SIGNUP = '/signup',
  TASKS = '/tasks',
  CLIENT = '/client',
  CLIENT_LEDGER = '/client-ledger',
  SERVICE = '/service',
  DEPARTMENT = '/department',
  PENDENCY = '/pendency',
  RESET_PASSWORD = '/reset-password',
  ROLE = '/role',
  BRANCH = '/branch',
  TELEPHONE_QUESTIONS = '/question',
  SUPERADMIN = '/superadmin',
  DEACTIVATE_USER = '/deactivate-user',
  REACTIVATE_USER = '/reactivate-user',
  DASHBOARD = '/dashboard',
  COLLECTION = '/collection',
  ORGANIZATION = '/organization',
  SCRIPTS = '/scripts',
  ORGANIZATION_CONFIGS = '/organization-configs',
}

export enum COMPONENTS {
  LOGIN = 'Login ',
  SIGNUP = 'Signup ',
  USER = 'User ',
  ROLE = 'Role ',
  BRANCH = 'Branch ',
  TELEPHONE_QUESTION = 'Telephone Question ',
}

export enum ERROR {
  PINNED_TASK_LIMIT = 'Only 3 tasks can be pinned at a time',
  NOT_FOUND = 'Not Found',
  INTERNAL_SERVER_ERROR = 'Internal Server Error',
  INVALID_OPERATION = 'Invalid Operation please refresh and try again',
  BAD_REQUEST = 'Bad Request',
  UNAUTHORIZED = 'Unauthorized',
  FORBIDDEN = 'Forbidden',
  INVALID_CREDENTIALS = 'Invalid Credentials',
  USER_ALREADY_EXISTS = 'User Already Exists',
  AADHAAR_ALREADY_EXISTS = 'Aadhaar Number Already Exists',
  ALREADY_EXISTS = 'Already Exists',
  USER_NOT_FOUND = 'User Not Found',
  USER_DEACTIVATED = 'User Deactivated',
  INVALID_TOKEN = 'Invalid Token',
  INVALID_PASSWORD = 'Invalid Password',
  INVALID_USER = 'Invalid User',
  INVALID_ROLE = "You don't have access to perform this action",
  INVALID_BRANCH = 'Invalid Branch',
  INVALID_USER_ROLE = 'Invalid User Role',
  PASSWORD_CANNOT_BE_EMPTY = 'Password field cannot be empty',
  USER_CANNOT_BE_CREATED = 'User cannot be created',
  EMAIL_REQUIRED = 'Email is required',
  EMAIL_ALREADY_EXISTS = 'Email Already Exists',
  TOKEN_NOT_FOUND = 'Token Not Found',
  TOKEN_EXPIRED = 'Token Expired',
  ORGANIZATION_NOT_FOUND = 'Organization Not Found',
  INVALId_TASK = 'Invalid Task',
  EMPLOYEE_NOT_FOUND = 'Employee Not Found',
  DEPARTMENT_NOT_FOUND = 'Department Not Found',
  LINKED_SERVICES = 'Linked Services Found, Please delete the services first',
  SERVICE_NOT_FOUND = 'Service Not Found',
  TASK_NOT_FOUND = 'Task Not Found',
  TASK_ALREADY_ACCEPTED_OR_COMPLETED = 'Task Already Accepted or Completed!!',
}
export enum SUCCESS {
  RECEIVED_LEDGER_BALANCE = 'Received Ledger Balance',
  CREATED = 'Created Successfully',
  UPDATED = 'Updated Successfully',
  DELETED = 'Deleted Successfully',
  FETCHED = 'Fetched Successfully',
  USER_LOGIN = 'User Login Successfully',
  USER_LOGOUT = 'User Logout Successfully',
  USER_RESET_PASSWORD = 'User Reset Password Successfully',
  LOGIN_SUCCESS = 'Login Successfully',
  USER_DEACTIVATED = 'User Deactivated Successfully',
  USER_REACTIVATED = 'User Reactivated Successfully',
  USER_UPDATED = 'User Updated Successfully',
  USER_DELETED = 'User Deleted Successfully',
  USER_NOT_FOUND = 'User Not Found',
  ROLE_FETCHED = 'Role Fetched Successfully',
  BLOCKED = 'Blocked Successfully',
  UNBLOCKED = 'Unblocked Successfully',
  EMPLOYEE_NOT_FOUND = 'Employee Not Found',
}
export enum ROLES {
  CLUSTER_HEAD = 'Cluster Head',
  BRANCH_MANAGER = 'Branch Manager',
  SUPERADMIN = 'Super Admin',
  SALES_MAN = 'Sales Man',
  BACKOFFICER = 'Back Officer',
  COLLECTION = 'Collection',
  COLLECTION_HEAD = 'Collection Head',
  TELECALLER = 'Telecaller',
}

export enum STEPS_NAMES {
  CUSTOMER = 'Customer',
  ADDRESS = 'Address',
  ASSOCIATE = 'Associate',
  INCOME = 'Income',
  LIABILITY = 'Liability',
  COLLATERAL = 'Collateral',
  BANK = 'Bank',
  PHOTOS = 'Photos',
  END = 'End',
}

export enum CURRENCY_SYMBOLS {
  INR = '₹',
  DOLLAR = '$',
  EURO = '€',
}
export enum PAYMENT_MODE {
  CASH = 'cash',
  ONLINE = 'online',
  NEFT = 'neft',
  IMPS = 'imps',
}

export const ORGANIZATION_STATUS = ['ACTIVE', 'DELETED', 'PENDING', 'BLOCKED'];
export enum STATUS {
  ACTIVE = 'ACTIVE',
  DELETED = 'DELETED',
  PENDING = 'PENDING',
  BLOCKED = 'BLOCKED',
}
export enum COMMIT_STATUS_ORDER {
  expired = 1,
  pending = 2,
  fulfilled = 3,
}
export enum StatusCodes {
  Continue = 100,
  SwitchingProtocols = 101,
  Processing = 102,
  EarlyHints = 103,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultiStatus = 207,
  AlreadyReported = 208,
  IMUsed = 226,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Found = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  TemporaryRedirect = 307,
  PermanentRedirect = 308,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  PayloadTooLarge = 413,
  URITooLong = 414,
  UnsupportedMediaType = 415,
  RangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  ImATeapot = 418,
  MisdirectedRequest = 421,
  UnprocessableEntity = 422,
  Locked = 423,
  FailedDependency = 424,
  TooEarly = 425,
  UpgradeRequired = 426,
  PreconditionRequired = 428,
  TooManyRequests = 429,
  RequestHeaderFieldsTooLarge = 431,
  UnavailableForLegalReasons = 451,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HTTPVersionNotSupported = 505,
  VariantAlsoNegotiates = 506,
  InsufficientStorage = 507,
  LoopDetected = 508,
  NotExtended = 510,
  NetworkAuthenticationRequired = 511,
}
