export const BANK = [
    { label: "Allahabad Bank", value: "allahabad_bank" },
    { label: "Andhra Bank", value: "andhra_bank" },
    { label: "Axis Bank", value: "axis_bank" },
    { label: "Bank of Bahrain and Kuwait", value: "bank_of_bahrain_and_kuwait" },
    { label: "Bank of Baroda - Corporate Banking", value: "bank_of_baroda_corporate" },
    { label: "Bank of Baroda - Retail Banking", value: "bank_of_baroda_retail" },
    { label: "Bank of India", value: "bank_of_india" },
    { label: "Bank of Maharashtra", value: "bank_of_maharashtra" },
    { label: "Canara Bank", value: "canara_bank" },
    { label: "Central Bank of India", value: "central_bank_of_india" },
    { label: "City Union Bank", value: "city_union_bank" },
    { label: "Corporation Bank", value: "corporation_bank" },
    { label: "Deutsche Bank", value: "deutsche_bank" },
    { label: "Development Credit Bank", value: "development_credit_bank" },
    { label: "Dhanlaxmi Bank", value: "dhanlaxmi_bank" },
    { label: "Federal Bank", value: "federal_bank" },
    { label: "ICICI Bank", value: "icici_bank" },
    { label: "IDBI Bank", value: "idbi_bank" },
    { label: "Indian Bank", value: "indian_bank" },
    { label: "Indian Overseas Bank", value: "indian_overseas_bank" },
    { label: "IndusInd Bank", value: "indusind_bank" },
    { label: "ING Vysya Bank", value: "ing_vysya_bank" },
    { label: "Jammu and Kashmir Bank", value: "jammu_kashmir_bank" },
    { label: "Karnataka Bank Ltd", value: "karnataka_bank" },
    { label: "Karur Vysya Bank", value: "karur_vysya_bank" },
    { label: "Kotak Bank", value: "kotak_bank" },
    { label: "Laxmi Vilas Bank", value: "laxmi_vilas_bank" },
    { label: "Oriental Bank of Commerce", value: "oriental_bank_of_commerce" },
    { label: "Punjab National Bank - Corporate Banking", value: "pnb_corporate" },
    { label: "Punjab National Bank - Retail Banking", value: "pnb_retail" },
    { label: "Punjab & Sind Bank", value: "punjab_sind_bank" },
    { label: "Shamrao Vitthal Co-operative Bank", value: "shamrao_vitthal_coop_bank" },
    { label: "South Indian Bank", value: "south_indian_bank" },
    { label: "State Bank of Bikaner & Jaipur", value: "sbbj" },
    { label: "State Bank of Hyderabad", value: "sbh" },
    { label: "State Bank of India", value: "sbi" },
    { label: "State Bank of Mysore", value: "sbm" },
    { label: "State Bank of Patiala", value: "sbp" },
    { label: "State Bank of Travancore", value: "sbt" },
    { label: "Syndicate Bank", value: "syndicate_bank" },
    { label: "Tamilnad Mercantile Bank Ltd.", value: "tamilnad_mercantile_bank" },
    { label: "UCO Bank", value: "uco_bank" },
    { label: "Union Bank of India", value: "union_bank_of_india" },
    { label: "United Bank of India", value: "united_bank_of_india" },
    { label: "Vijaya Bank", value: "vijaya_bank" },
    { label: "Yes Bank Ltd", value: "yes_bank" },
  ];
  