export const CITIES = [
{
    "Andaman and Nicobar Islands": [
      "Port Blair"
    ],
    "Haryana":[
        { label: "Faridabad", value: "Faridabad" },
        { label: "Gurgaon", value: "Gurgaon" },
        { label: "Hisar", value: "Hisar" },
        { label: "Rohtak", value: "Rohtak" },
        { label: "Panipat", value: "Panipat" },
        { label: "Karnal", value: "Karnal" },
        { label: "Sonipat", value: "Sonipat" },
        { label: "Yamunanagar", value: "Yamunanagar" },
        { label: "Panchkula", value: "Panchkula" },
        { label: "Bhiwani", value: "Bhiwani" },
        { label: "Bahadurgarh", value: "Bahadurgarh" },
        { label: "Jind", value: "Jind" },
        { label: "Sirsa", value: "Sirsa" },
        { label: "Thanesar", value: "Thanesar" },
        { label: "Kaithal", value: "Kaithal" },
        { label: "Palwal", value: "Palwal" },
        { label: "Rewari", value: "Rewari" },
        { label: "Hansi", value: "Hansi" },
        { label: "Narnaul", value: "Narnaul" },
        { label: "Fatehabad", value: "Fatehabad" },
        { label: "Gohana", value: "Gohana" },
        { label: "Tohana", value: "Tohana" },
        { label: "Narwana", value: "Narwana" },
        { label: "Mandi Dabwali", value: "Mandi Dabwali" },
        { label: "Charkhi Dadri", value: "Charkhi Dadri" },
        { label: "Shahbad", value: "Shahbad" },
        { label: "Pehowa", value: "Pehowa" },
        { label: "Samalkha", value: "Samalkha" },
        { label: "Pinjore", value: "Pinjore" },
        { label: "Ladwa", value: "Ladwa" },
        { label: "Sohna", value: "Sohna" },
        { label: "Safidon", value: "Safidon" },
        { label: "Taraori", value: "Taraori" },
        { label: "Mahendragarh", value: "Mahendragarh" },
        { label: "Ratia", value: "Ratia" },
        { label: "Rania", value: "Rania" },
        { label: "Sarsod", value: "Sarsod" }
      ],
      
    "Tamil Nadu":[
        { label: "Chennai", value: "Chennai" },
        { label: "Coimbatore", value: "Coimbatore" },
        { label: "Madurai", value: "Madurai" },
        { label: "Tiruchirappalli", value: "Tiruchirappalli" },
        { label: "Salem", value: "Salem" },
        { label: "Tirunelveli", value: "Tirunelveli" },
        { label: "Tiruppur", value: "Tiruppur" },
        { label: "Ranipet", value: "Ranipet" },
        { label: "Nagercoil", value: "Nagercoil" },
        { label: "Thanjavur", value: "Thanjavur" },
        { label: "Vellore", value: "Vellore" },
        { label: "Kancheepuram", value: "Kancheepuram" },
        { label: "Erode", value: "Erode" },
        { label: "Tiruvannamalai", value: "Tiruvannamalai" },
        { label: "Pollachi", value: "Pollachi" },
        { label: "Rajapalayam", value: "Rajapalayam" },
        { label: "Sivakasi", value: "Sivakasi" },
        { label: "Pudukkottai", value: "Pudukkottai" },
        { label: "Neyveli (TS)", value: "Neyveli (TS)" },
        { label: "Nagapattinam", value: "Nagapattinam" },
        { label: "Viluppuram", value: "Viluppuram" },
        { label: "Tiruchengode", value: "Tiruchengode" },
        { label: "Vaniyambadi", value: "Vaniyambadi" },
        { label: "Theni Allinagaram", value: "Theni Allinagaram" },
        { label: "Udhagamandalam", value: "Udhagamandalam" },
        { label: "Aruppukkottai", value: "Aruppukkottai" },
        { label: "Paramakudi", value: "Paramakudi" },
        { label: "Arakkonam", value: "Arakkonam" },
        { label: "Virudhachalam", value: "Virudhachalam" },
        { label: "Srivilliputhur", value: "Srivilliputhur" },
        { label: "Tindivanam", value: "Tindivanam" },
        { label: "Virudhunagar", value: "Virudhunagar" },
        { label: "Karur", value: "Karur" },
        { label: "Valparai", value: "Valparai" },
        { label: "Sankarankovil", value: "Sankarankovil" },
        { label: "Tenkasi", value: "Tenkasi" },
        { label: "Palani", value: "Palani" },
        { label: "Pattukkottai", value: "Pattukkottai" },
        { label: "Tirupathur", value: "Tirupathur" },
        { label: "Ramanathapuram", value: "Ramanathapuram" },
        { label: "Udumalaipettai", value: "Udumalaipettai" },
        { label: "Gobichettipalayam", value: "Gobichettipalayam" },
        { label: "Thiruvarur", value: "Thiruvarur" },
        { label: "Thiruvallur", value: "Thiruvallur" },
        { label: "Panruti", value: "Panruti" },
        { label: "Namakkal", value: "Namakkal" },
        { label: "Thirumangalam", value: "Thirumangalam" },
        { label: "Vikramasingapuram", value: "Vikramasingapuram" },
        { label: "Nellikuppam", value: "Nellikuppam" },
        { label: "Rasipuram", value: "Rasipuram" },
        { label: "Tiruttani", value: "Tiruttani" },
        { label: "Nandivaram-Guduvancheri", value: "Nandivaram-Guduvancheri" },
        { label: "Periyakulam", value: "Periyakulam" },
        { label: "Pernampattu", value: "Pernampattu" },
        { label: "Vellakoil", value: "Vellakoil" },
        { label: "Sivaganga", value: "Sivaganga" },
        { label: "Vadalur", value: "Vadalur" },
        { label: "Rameshwaram", value: "Rameshwaram" },
        { label: "Tiruvethipuram", value: "Tiruvethipuram" },
        { label: "Perambalur", value: "Perambalur" },
        { label: "Usilampatti", value: "Usilampatti" },
        { label: "Vedaranyam", value: "Vedaranyam" },
        { label: "Sathyamangalam", value: "Sathyamangalam" },
        { label: "Puliyankudi", value: "Puliyankudi" },
        { label: "Nanjikottai", value: "Nanjikottai" },
        { label: "Thuraiyur", value: "Thuraiyur" },
        { label: "Sirkali", value: "Sirkali" },
        { label: "Tiruchendur", value: "Tiruchendur" },
        { label: "Periyasemur", value: "Periyasemur" },
        { label: "Sattur", value: "Sattur" },
        { label: "Vandavasi", value: "Vandavasi" },
        { label: "Tharamangalam", value: "Tharamangalam" },
        { label: "Tirukkoyilur", value: "Tirukkoyilur" },
        { label: "Oddanchatram", value: "Oddanchatram" },
        { label: "Palladam", value: "Palladam" },
        { label: "Vadakkuvalliyur", value: "Vadakkuvalliyur" },
        { label: "Tirukalukundram", value: "Tirukalukundram" },
        { label: "Uthamapalayam", value: "Uthamapalayam" },
        { label: "Surandai", value: "Surandai" },
        { label: "Sankari", value: "Sankari" },
        { label: "Shenkottai", value: "Shenkottai" },
        { label: "Vadipatti", value: "Vadipatti" },
        { label: "Sholingur", value: "Sholingur" },
        { label: "Tirupathur", value: "Tirupathur" },
        { label: "Manachanallur", value: "Manachanallur" },
        { label: "Viswanatham", value: "Viswanatham" },
        { label: "Polur", value: "Polur" },
        { label: "Panagudi", value: "Panagudi" },
        { label: "Uthiramerur", value: "Uthiramerur" },
        { label: "Thiruthuraipoondi", value: "Thiruthuraipoondi" },
        { label: "Pallapatti", value: "Pallapatti" },
        { label: "Ponneri", value: "Ponneri" },
        { label: "Lalgudi", value: "Lalgudi" },
        { label: "Natham", value: "Natham" },
        { label: "Unnamalaikadai", value: "Unnamalaikadai" },
        { label: "P.N.Patti", value: "P.N.Patti" },
        { label: "Tharangambadi", value: "Tharangambadi" },
        { label: "Tittakudi", value: "Tittakudi" },
        { label: "Pacode", value: "Pacode" },
        { label: "O' Valley", value: "O' Valley" },
        { label: "Suriyampalayam", value: "Suriyampalayam" },
        { label: "Sholavandan", value: "Sholavandan" },
        { label: "Thammampatti", value: "Thammampatti" },
        { label: "Namagiripettai", value: "Namagiripettai" },
        { label: "Peravurani", value: "Peravurani" },
        { label: "Parangipettai", value: "Parangipettai" },
        { label: "Pudupattinam", value: "Pudupattinam" },
        { label: "Pallikonda", value: "Pallikonda" },
        { label: "Sivagiri", value: "Sivagiri" },
        { label: "Punjaipugalur", value: "Punjaipugalur" },
        { label: "Padmanabhapuram", value: "Padmanabhapuram" },
        { label: "Thirupuvanam", value: "Thirupuvanam" }
      ],
      
    "Madhya Pradesh":[
        { label: "Indore", value: "Indore" },
        { label: "Bhopal", value: "Bhopal" },
        { label: "Jabalpur", value: "Jabalpur" },
        { label: "Gwalior", value: "Gwalior" },
        { label: "Ujjain", value: "Ujjain" },
        { label: "Sagar", value: "Sagar" },
        { label: "Ratlam", value: "Ratlam" },
        { label: "Satna", value: "Satna" },
        { label: "Murwara (Katni)", value: "Murwara (Katni)" },
        { label: "Morena", value: "Morena" },
        { label: "Singrauli", value: "Singrauli" },
        { label: "Rewa", value: "Rewa" },
        { label: "Vidisha", value: "Vidisha" },
        { label: "Ganjbasoda", value: "Ganjbasoda" },
        { label: "Shivpuri", value: "Shivpuri" },
        { label: "Mandsaur", value: "Mandsaur" },
        { label: "Neemuch", value: "Neemuch" },
        { label: "Nagda", value: "Nagda" },
        { label: "Itarsi", value: "Itarsi" },
        { label: "Sarni", value: "Sarni" },
        { label: "Sehore", value: "Sehore" },
        { label: "Mhow Cantonment", value: "Mhow Cantonment" },
        { label: "Seoni", value: "Seoni" },
        { label: "Balaghat", value: "Balaghat" },
        { label: "Ashok Nagar", value: "Ashok Nagar" },
        { label: "Tikamgarh", value: "Tikamgarh" },
        { label: "Shahdol", value: "Shahdol" },
        { label: "Pithampur", value: "Pithampur" },
        { label: "Alirajpur", value: "Alirajpur" },
        { label: "Mandla", value: "Mandla" },
        { label: "Sheopur", value: "Sheopur" },
        { label: "Shajapur", value: "Shajapur" },
        { label: "Panna", value: "Panna" },
        { label: "Raghogarh-Vijaypur", value: "Raghogarh-Vijaypur" },
        { label: "Sendhwa", value: "Sendhwa" },
        { label: "Sidhi", value: "Sidhi" },
        { label: "Pipariya", value: "Pipariya" },
        { label: "Shujalpur", value: "Shujalpur" },
        { label: "Sironj", value: "Sironj" },
        { label: "Pandhurna", value: "Pandhurna" },
        { label: "Nowgong", value: "Nowgong" },
        { label: "Mandideep", value: "Mandideep" },
        { label: "Sihora", value: "Sihora" },
        { label: "Raisen", value: "Raisen" },
        { label: "Lahar", value: "Lahar" },
        { label: "Maihar", value: "Maihar" },
        { label: "Sanawad", value: "Sanawad" },
        { label: "Sabalgarh", value: "Sabalgarh" },
        { label: "Umaria", value: "Umaria" },
        { label: "Porsa", value: "Porsa" },
        { label: "Narsinghgarh", value: "Narsinghgarh" },
        { label: "Malaj Khand", value: "Malaj Khand" },
        { label: "Sarangpur", value: "Sarangpur" },
        { label: "Mundi", value: "Mundi" },
        { label: "Nepanagar", value: "Nepanagar" },
        { label: "Pasan", value: "Pasan" },
        { label: "Mahidpur", value: "Mahidpur" },
        { label: "Seoni-Malwa", value: "Seoni-Malwa" },
        { label: "Rehli", value: "Rehli" },
        { label: "Manawar", value: "Manawar" },
        { label: "Rahatgarh", value: "Rahatgarh" },
        { label: "Panagar", value: "Panagar" },
        { label: "Wara Seoni", value: "Wara Seoni" },
        { label: "Tarana", value: "Tarana" },
        { label: "Sausar", value: "Sausar" },
        { label: "Rajgarh", value: "Rajgarh" },
        { label: "Niwari", value: "Niwari" },
        { label: "Mauganj", value: "Mauganj" },
        { label: "Manasa", value: "Manasa" },
        { label: "Nainpur", value: "Nainpur" },
        { label: "Prithvipur", value: "Prithvipur" },
        { label: "Sohagpur", value: "Sohagpur" },
        { label: "Nowrozabad (Khodargama)", value: "Nowrozabad (Khodargama)" },
        { label: "Shamgarh", value: "Shamgarh" },
        { label: "Maharajpur", value: "Maharajpur" },
        { label: "Multai", value: "Multai" },
        { label: "Pali", value: "Pali" },
        { label: "Pachore", value: "Pachore" },
        { label: "Rau", value: "Rau" },
        { label: "Mhowgaon", value: "Mhowgaon" },
        { label: "Vijaypur", value: "Vijaypur" },
        { label: "Narsinghgarh", value: "Narsinghgarh" }
      ],
      
    "Jharkhand":[
        { label: "Dhanbad", value: "Dhanbad" },
        { label: "Ranchi", value: "Ranchi" },
        { label: "Jamshedpur", value: "Jamshedpur" },
        { label: "Bokaro Steel City", value: "Bokaro Steel City" },
        { label: "Deoghar", value: "Deoghar" },
        { label: "Phusro", value: "Phusro" },
        { label: "Adityapur", value: "Adityapur" },
        { label: "Hazaribag", value: "Hazaribag" },
        { label: "Giridih", value: "Giridih" },
        { label: "Ramgarh", value: "Ramgarh" },
        { label: "Jhumri Tilaiya", value: "Jhumri Tilaiya" },
        { label: "Saunda", value: "Saunda" },
        { label: "Sahibganj", value: "Sahibganj" },
        { label: "Medininagar (Daltonganj)", value: "Medininagar (Daltonganj)" },
        { label: "Chaibasa", value: "Chaibasa" },
        { label: "Chatra", value: "Chatra" },
        { label: "Gumia", value: "Gumia" },
        { label: "Dumka", value: "Dumka" },
        { label: "Madhupur", value: "Madhupur" },
        { label: "Chirkunda", value: "Chirkunda" },
        { label: "Pakaur", value: "Pakaur" },
        { label: "Simdega", value: "Simdega" },
        { label: "Musabani", value: "Musabani" },
        { label: "Mihijam", value: "Mihijam" },
        { label: "Patratu", value: "Patratu" },
        { label: "Lohardaga", value: "Lohardaga" },
        { label: "Tenu dam-cum-Kathhara", value: "Tenu dam-cum-Kathhara" }
      ],
      
    "Mizoram":[
        { label: "Aizawl", value: "Aizawl" },
        { label: "Lunglei", value: "Lunglei" },
        { label: "Saiha", value: "Saiha" }
      ],
      
    "Nagaland":  [
        { label: "Dimapur", value: "Dimapur" },
        { label: "Kohima", value: "Kohima" },
        { label: "Zunheboto", value: "Zunheboto" },
        { label: "Tuensang", value: "Tuensang" },
        { label: "Wokha", value: "Wokha" },
        { label: "Mokokchung", value: "Mokokchung" }
      ],
    "Himachal Pradesh":[
        { label: "Shimla", value: "Shimla" },
        { label: "Mandi", value: "Mandi" },
        { label: "Solan", value: "Solan" },
        { label: "Nahan", value: "Nahan" },
        { label: "Sundarnagar", value: "Sundarnagar" },
        { label: "Palampur", value: "Palampur" },
        { label: "Kullu", value: "Kullu" }
      ],
    "Tripura":[
        { label: "Agartala", value: "Agartala" },
        { label: "Udaipur", value: "Udaipur" },
        { label: "Dharmanagar", value: "Dharmanagar" },
        { label: "Pratapgarh", value: "Pratapgarh" },
        { label: "Kailasahar", value: "Kailasahar" },
        { label: "Belonia", value: "Belonia" },
        { label: "Khowai", value: "Khowai" }
      ],
    "Andhra Pradesh":[
        { label: "Visakhapatnam", value: "Visakhapatnam" },
        { label: "Vijayawada", value: "Vijayawada" },
        { label: "Guntur", value: "Guntur" },
        { label: "Nellore", value: "Nellore" },
        { label: "Kurnool", value: "Kurnool" },
        { label: "Rajahmundry", value: "Rajahmundry" },
        { label: "Kakinada", value: "Kakinada" },
        { label: "Tirupati", value: "Tirupati" },
        { label: "Anantapur", value: "Anantapur" },
        { label: "Kadapa", value: "Kadapa" },
        { label: "Vizianagaram", value: "Vizianagaram" },
        { label: "Eluru", value: "Eluru" },
        { label: "Ongole", value: "Ongole" },
        { label: "Nandyal", value: "Nandyal" },
        { label: "Machilipatnam", value: "Machilipatnam" },
        { label: "Adoni", value: "Adoni" },
        { label: "Tenali", value: "Tenali" },
        { label: "Chittoor", value: "Chittoor" },
        { label: "Hindupur", value: "Hindupur" },
        { label: "Proddatur", value: "Proddatur" },
        { label: "Bhimavaram", value: "Bhimavaram" },
        { label: "Madanapalle", value: "Madanapalle" },
        { label: "Guntakal", value: "Guntakal" },
        { label: "Dharmavaram", value: "Dharmavaram" },
        { label: "Gudivada", value: "Gudivada" },
        { label: "Srikakulam", value: "Srikakulam" },
        { label: "Narasaraopet", value: "Narasaraopet" },
        { label: "Rajampet", value: "Rajampet" },
        { label: "Tadpatri", value: "Tadpatri" },
        { label: "Tadepalligudem", value: "Tadepalligudem" },
        { label: "Chilakaluripet", value: "Chilakaluripet" },
        { label: "Yemmiganur", value: "Yemmiganur" },
        { label: "Kadiri", value: "Kadiri" },
        { label: "Chirala", value: "Chirala" },
        { label: "Anakapalle", value: "Anakapalle" },
        { label: "Kavali", value: "Kavali" },
        { label: "Palacole", value: "Palacole" },
        { label: "Sullurpeta", value: "Sullurpeta" },
        { label: "Tanuku", value: "Tanuku" },
        { label: "Rayachoti", value: "Rayachoti" },
        { label: "Srikalahasti", value: "Srikalahasti" },
        { label: "Bapatla", value: "Bapatla" },
        { label: "Naidupet", value: "Naidupet" },
        { label: "Nagari", value: "Nagari" },
        { label: "Gudur", value: "Gudur" },
        { label: "Vinukonda", value: "Vinukonda" },
        { label: "Narasapuram", value: "Narasapuram" },
        { label: "Nuzvid", value: "Nuzvid" },
        { label: "Markapur", value: "Markapur" },
        { label: "Ponnur", value: "Ponnur" },
        { label: "Kandukur", value: "Kandukur" },
        { label: "Bobbili", value: "Bobbili" },
        { label: "Rayadurg", value: "Rayadurg" },
        { label: "Samalkot", value: "Samalkot" },
        { label: "Jaggaiahpet", value: "Jaggaiahpet" },
        { label: "Tuni", value: "Tuni" },
        { label: "Amalapuram", value: "Amalapuram" },
        { label: "Bheemunipatnam", value: "Bheemunipatnam" },
        { label: "Venkatagiri", value: "Venkatagiri" },
        { label: "Sattenapalle", value: "Sattenapalle" },
        { label: "Pithapuram", value: "Pithapuram" },
        { label: "Palasa Kasibugga", value: "Palasa Kasibugga" },
        { label: "Parvathipuram", value: "Parvathipuram" },
        { label: "Macherla", value: "Macherla" },
        { label: "Gooty", value: "Gooty" },
        { label: "Salur", value: "Salur" },
        { label: "Mandapeta", value: "Mandapeta" },
        { label: "Jammalamadugu", value: "Jammalamadugu" },
        { label: "Peddapuram", value: "Peddapuram" },
        { label: "Punganur", value: "Punganur" },
        { label: "Nidadavole", value: "Nidadavole" },
        { label: "Repalle", value: "Repalle" },
        { label: "Ramachandrapuram", value: "Ramachandrapuram" },
        { label: "Kovvur", value: "Kovvur" },
        { label: "Tiruvuru", value: "Tiruvuru" },
        { label: "Uravakonda", value: "Uravakonda" },
        { label: "Narsipatnam", value: "Narsipatnam" },
        { label: "Yerraguntla", value: "Yerraguntla" },
        { label: "Pedana", value: "Pedana" },
        { label: "Puttur", value: "Puttur" },
        { label: "Renigunta", value: "Renigunta" },
        { label: "Rajam", value: "Rajam" },
        { label: "Srisailam Project (Right Flank Colony) Township", value: "Srisailam Project (Right Flank Colony) Township" }
      ],
      
    "Punjab":[
        { label: "Ludhiana", value: "Ludhiana" },
        { label: "Patiala", value: "Patiala" },
        { label: "Amritsar", value: "Amritsar" },
        { label: "Jalandhar", value: "Jalandhar" },
        { label: "Bathinda", value: "Bathinda" },
        { label: "Pathankot", value: "Pathankot" },
        { label: "Hoshiarpur", value: "Hoshiarpur" },
        { label: "Batala", value: "Batala" },
        { label: "Moga", value: "Moga" },
        { label: "Malerkotla", value: "Malerkotla" },
        { label: "Khanna", value: "Khanna" },
        { label: "Mohali", value: "Mohali" },
        { label: "Barnala", value: "Barnala" },
        { label: "Firozpur", value: "Firozpur" },
        { label: "Phagwara", value: "Phagwara" },
        { label: "Kapurthala", value: "Kapurthala" },
        { label: "Zirakpur", value: "Zirakpur" },
        { label: "Kot Kapura", value: "Kot Kapura" },
        { label: "Faridkot", value: "Faridkot" },
        { label: "Muktsar", value: "Muktsar" },
        { label: "Rajpura", value: "Rajpura" },
        { label: "Sangrur", value: "Sangrur" },
        { label: "Fazilka", value: "Fazilka" },
        { label: "Gurdaspur", value: "Gurdaspur" },
        { label: "Kharar", value: "Kharar" },
        { label: "Gobindgarh", value: "Gobindgarh" },
        { label: "Mansa", value: "Mansa" },
        { label: "Malout", value: "Malout" },
        { label: "Nabha", value: "Nabha" },
        { label: "Tarn Taran", value: "Tarn Taran" },
        { label: "Jagraon", value: "Jagraon" },
        { label: "Sunam", value: "Sunam" },
        { label: "Dhuri", value: "Dhuri" },
        { label: "Firozpur Cantt.", value: "Firozpur Cantt." },
        { label: "Sirhind Fatehgarh Sahib", value: "Sirhind Fatehgarh Sahib" },
        { label: "Rupnagar", value: "Rupnagar" },
        { label: "Jalandhar Cantt.", value: "Jalandhar Cantt." },
        { label: "Samana", value: "Samana" },
        { label: "Nawanshahr", value: "Nawanshahr" },
        { label: "Rampura Phul", value: "Rampura Phul" },
        { label: "Nangal", value: "Nangal" },
        { label: "Nakodar", value: "Nakodar" },
        { label: "Zira", value: "Zira" },
        { label: "Patti", value: "Patti" },
        { label: "Raikot", value: "Raikot" },
        { label: "Longowal", value: "Longowal" },
        { label: "Urmar Tanda", value: "Urmar Tanda" },
        { label: "Morinda, India", value: "Morinda, India" },
        { label: "Phillaur", value: "Phillaur" },
        { label: "Pattran", value: "Pattran" },
        { label: "Qadian", value: "Qadian" },
        { label: "Sujanpur", value: "Sujanpur" },
        { label: "Mukerian", value: "Mukerian" },
        { label: "Talwara", value: "Talwara" }
      ],
      
    "Chandigarh":[
        { label: "Chandigarh", value: "Chandigarh" }
      ],
    "Rajasthan":[
        { label: "Jaipur", value: "Jaipur" },
        { label: "Jodhpur", value: "Jodhpur" },
        { label: "Bikaner", value: "Bikaner" },
        { label: "Udaipur", value: "Udaipur" },
        { label: "Ajmer", value: "Ajmer" },
        { label: "Bhilwara", value: "Bhilwara" },
        { label: "Alwar", value: "Alwar" },
        { label: "Bharatpur", value: "Bharatpur" },
        { label: "Pali", value: "Pali" },
        { label: "Barmer", value: "Barmer" },
        { label: "Sikar", value: "Sikar" },
        { label: "Tonk", value: "Tonk" },
        { label: "Sadulpur", value: "Sadulpur" },
        { label: "Sawai Madhopur", value: "Sawai Madhopur" },
        { label: "Nagaur", value: "Nagaur" },
        { label: "Makrana", value: "Makrana" },
        { label: "Sujangarh", value: "Sujangarh" },
        { label: "Sardarshahar", value: "Sardarshahar" },
        { label: "Ladnu", value: "Ladnu" },
        { label: "Ratangarh", value: "Ratangarh" },
        { label: "Nokha", value: "Nokha" },
        { label: "Nimbahera", value: "Nimbahera" },
        { label: "Suratgarh", value: "Suratgarh" },
        { label: "Rajsamand", value: "Rajsamand" },
        { label: "Lachhmangarh", value: "Lachhmangarh" },
        { label: "Rajgarh (Churu)", value: "Rajgarh (Churu)" },
        { label: "Nasirabad", value: "Nasirabad" },
        { label: "Nohar", value: "Nohar" },
        { label: "Phalodi", value: "Phalodi" },
        { label: "Nathdwara", value: "Nathdwara" },
        { label: "Pilani", value: "Pilani" },
        { label: "Merta City", value: "Merta City" },
        { label: "Sojat", value: "Sojat" },
        { label: "Neem-Ka-Thana", value: "Neem-Ka-Thana" },
        { label: "Sirohi", value: "Sirohi" },
        { label: "Pratapgarh", value: "Pratapgarh" },
        { label: "Rawatbhata", value: "Rawatbhata" },
        { label: "Sangaria", value: "Sangaria" },
        { label: "Lalsot", value: "Lalsot" },
        { label: "Pilibanga", value: "Pilibanga" },
        { label: "Pipar City", value: "Pipar City" },
        { label: "Taranagar", value: "Taranagar" },
        { label: "Vijainagar, Ajmer", value: "Vijainagar, Ajmer" },
        { label: "Sumerpur", value: "Sumerpur" },
        { label: "Sagwara", value: "Sagwara" },
        { label: "Ramganj Mandi", value: "Ramganj Mandi" },
        { label: "Lakheri", value: "Lakheri" },
        { label: "Udaipurwati", value: "Udaipurwati" },
        { label: "Losal", value: "Losal" },
        { label: "Sri Madhopur", value: "Sri Madhopur" },
        { label: "Ramngarh", value: "Ramngarh" },
        { label: "Rawatsar", value: "Rawatsar" },
        { label: "Rajakhera", value: "Rajakhera" },
        { label: "Shahpura", value: "Shahpura" },
        { label: "Shahpura", value: "Shahpura" },
        { label: "Raisinghnagar", value: "Raisinghnagar" },
        { label: "Malpura", value: "Malpura" },
        { label: "Nadbai", value: "Nadbai" },
        { label: "Sanchore", value: "Sanchore" },
        { label: "Nagar", value: "Nagar" },
        { label: "Rajgarh (Alwar)", value: "Rajgarh (Alwar)" },
        { label: "Sheoganj", value: "Sheoganj" },
        { label: "Sadri", value: "Sadri" },
        { label: "Todaraisingh", value: "Todaraisingh" },
        { label: "Todabhim", value: "Todabhim" },
        { label: "Reengus", value: "Reengus" },
        { label: "Rajaldesar", value: "Rajaldesar" },
        { label: "Sadulshahar", value: "Sadulshahar" },
        { label: "Sambhar", value: "Sambhar" },
        { label: "Prantij", value: "Prantij" },
        { label: "Mount Abu", value: "Mount Abu" },
        { label: "Mangrol", value: "Mangrol" },
        { label: "Phulera", value: "Phulera" },
        { label: "Mandawa", value: "Mandawa" },
        { label: "Pindwara", value: "Pindwara" },
        { label: "Mandalgarh", value: "Mandalgarh" },
        { label: "Takhatgarh", value: "Takhatgarh" }
      ],
      
    "Assam":[
        { label: "Guwahati", value: "Guwahati" },
        { label: "Silchar", value: "Silchar" },
        { label: "Dibrugarh", value: "Dibrugarh" },
        { label: "Nagaon", value: "Nagaon" },
        { label: "Tinsukia", value: "Tinsukia" },
        { label: "Jorhat", value: "Jorhat" },
        { label: "Bongaigaon City", value: "Bongaigaon City" },
        { label: "Dhubri", value: "Dhubri" },
        { label: "Diphu", value: "Diphu" },
        { label: "North Lakhimpur", value: "North Lakhimpur" },
        { label: "Tezpur", value: "Tezpur" },
        { label: "Karimganj", value: "Karimganj" },
        { label: "Sibsagar", value: "Sibsagar" },
        { label: "Goalpara", value: "Goalpara" },
        { label: "Barpeta", value: "Barpeta" },
        { label: "Lanka", value: "Lanka" },
        { label: "Lumding", value: "Lumding" },
        { label: "Mankachar", value: "Mankachar" },
        { label: "Nalbari", value: "Nalbari" },
        { label: "Rangia", value: "Rangia" },
        { label: "Margherita", value: "Margherita" },
        { label: "Mangaldoi", value: "Mangaldoi" },
        { label: "Silapathar", value: "Silapathar" },
        { label: "Mariani", value: "Mariani" },
        { label: "Marigaon", value: "Marigaon" }
      ],
      
    "Odisha":[
        { label: "Bhubaneswar", value: "Bhubaneswar" },
        { label: "Cuttack", value: "Cuttack" },
        { label: "Raurkela", value: "Raurkela" },
        { label: "Brahmapur", value: "Brahmapur" },
        { label: "Sambalpur", value: "Sambalpur" },
        { label: "Puri", value: "Puri" },
        { label: "Baleshwar Town", value: "Baleshwar Town" },
        { label: "Baripada Town", value: "Baripada Town" },
        { label: "Bhadrak", value: "Bhadrak" },
        { label: "Balangir", value: "Balangir" },
        { label: "Jharsuguda", value: "Jharsuguda" },
        { label: "Bargarh", value: "Bargarh" },
        { label: "Paradip", value: "Paradip" },
        { label: "Bhawanipatna", value: "Bhawanipatna" },
        { label: "Dhenkanal", value: "Dhenkanal" },
        { label: "Barbil", value: "Barbil" },
        { label: "Kendujhar", value: "Kendujhar" },
        { label: "Sunabeda", value: "Sunabeda" },
        { label: "Rayagada", value: "Rayagada" },
        { label: "Jatani", value: "Jatani" },
        { label: "Byasanagar", value: "Byasanagar" },
        { label: "Kendrapara", value: "Kendrapara" },
        { label: "Rajagangapur", value: "Rajagangapur" },
        { label: "Parlakhemundi", value: "Parlakhemundi" },
        { label: "Talcher", value: "Talcher" },
        { label: "Sundargarh", value: "Sundargarh" },
        { label: "Phulabani", value: "Phulabani" },
        { label: "Pattamundai", value: "Pattamundai" },
        { label: "Titlagarh", value: "Titlagarh" },
        { label: "Nabarangapur", value: "Nabarangapur" },
        { label: "Soro", value: "Soro" },
        { label: "Malkangiri", value: "Malkangiri" },
        { label: "Rairangpur", value: "Rairangpur" },
        { label: "Tarbha", value: "Tarbha" }
      ],
      
    "Chhattisgarh":[
        { label: "Raipur", value: "Raipur" },
        { label: "Bhilai Nagar", value: "Bhilai Nagar" },
        { label: "Korba", value: "Korba" },
        { label: "Bilaspur", value: "Bilaspur" },
        { label: "Durg", value: "Durg" },
        { label: "Rajnandgaon", value: "Rajnandgaon" },
        { label: "Jagdalpur", value: "Jagdalpur" },
        { label: "Raigarh", value: "Raigarh" },
        { label: "Ambikapur", value: "Ambikapur" },
        { label: "Mahasamund", value: "Mahasamund" },
        { label: "Dhamtari", value: "Dhamtari" },
        { label: "Chirmiri", value: "Chirmiri" },
        { label: "Bhatapara", value: "Bhatapara" },
        { label: "Dalli-Rajhara", value: "Dalli-Rajhara" },
        { label: "Naila Janjgir", value: "Naila Janjgir" },
        { label: "Tilda Newra", value: "Tilda Newra" },
        { label: "Mungeli", value: "Mungeli" },
        { label: "Manendragarh", value: "Manendragarh" },
        { label: "Sakti", value: "Sakti" }
      ],
      
    "Jammu and Kashmir":[
        { label: "Srinagar", value: "Srinagar" },
        { label: "Jammu", value: "Jammu" },
        { label: "Baramula", value: "Baramula" },
        { label: "Anantnag", value: "Anantnag" },
        { label: "Sopore", value: "Sopore" },
        { label: "KathUrban Agglomeration", value: "KathUrban Agglomeration" },
        { label: "Rajauri", value: "Rajauri" },
        { label: "Punch", value: "Punch" },
        { label: "Udhampur", value: "Udhampur" }
      ],
      
    "Karnataka":[
        { label: "Bengaluru", value: "Bengaluru" },
        { label: "Hubli-Dharwad", value: "Hubli-Dharwad" },
        { label: "Belagavi", value: "Belagavi" },
        { label: "Mangaluru", value: "Mangaluru" },
        { label: "Davanagere", value: "Davanagere" },
        { label: "Ballari", value: "Ballari" },
        { label: "Mysore", value: "Mysore" },
        { label: "Tumkur", value: "Tumkur" },
        { label: "Shivamogga", value: "Shivamogga" },
        { label: "Raayachuru", value: "Raayachuru" },
        { label: "Robertson Pet", value: "Robertson Pet" },
        { label: "Kolar", value: "Kolar" },
        { label: "Mandya", value: "Mandya" },
        { label: "Udupi", value: "Udupi" },
        { label: "Chikkamagaluru", value: "Chikkamagaluru" },
        { label: "Karwar", value: "Karwar" },
        { label: "Ranebennuru", value: "Ranebennuru" },
        { label: "Ranibennur", value: "Ranibennur" },
        { label: "Ramanagaram", value: "Ramanagaram" },
        { label: "Gokak", value: "Gokak" },
        { label: "Yadgir", value: "Yadgir" },
        { label: "Rabkavi Banhatti", value: "Rabkavi Banhatti" },
        { label: "Shahabad", value: "Shahabad" },
        { label: "Sirsi", value: "Sirsi" },
        { label: "Sindhnur", value: "Sindhnur" },
        { label: "Tiptur", value: "Tiptur" },
        { label: "Arsikere", value: "Arsikere" },
        { label: "Nanjangud", value: "Nanjangud" },
        { label: "Sagara", value: "Sagara" },
        { label: "Sira", value: "Sira" },
        { label: "Puttur", value: "Puttur" },
        { label: "Athni", value: "Athni" },
        { label: "Mulbagal", value: "Mulbagal" },
        { label: "Surapura", value: "Surapura" },
        { label: "Siruguppa", value: "Siruguppa" },
        { label: "Mudhol", value: "Mudhol" },
        { label: "Sidlaghatta", value: "Sidlaghatta" },
        { label: "Shahpur", value: "Shahpur" },
        { label: "Saundatti-Yellamma", value: "Saundatti-Yellamma" },
        { label: "Wadi", value: "Wadi" },
        { label: "Manvi", value: "Manvi" },
        { label: "Nelamangala", value: "Nelamangala" },
        { label: "Lakshmeshwar", value: "Lakshmeshwar" },
        { label: "Ramdurg", value: "Ramdurg" },
        { label: "Nargund", value: "Nargund" },
        { label: "Tarikere", value: "Tarikere" },
        { label: "Malavalli", value: "Malavalli" },
        { label: "Savanur", value: "Savanur" },
        { label: "Lingsugur", value: "Lingsugur" },
        { label: "Vijayapura", value: "Vijayapura" },
        { label: "Sankeshwara", value: "Sankeshwara" },
        { label: "Madikeri", value: "Madikeri" },
        { label: "Talikota", value: "Talikota" },
        { label: "Sedam", value: "Sedam" },
        { label: "Shikaripur", value: "Shikaripur" },
        { label: "Mahalingapura", value: "Mahalingapura" },
        { label: "Mudalagi", value: "Mudalagi" },
        { label: "Muddebihal", value: "Muddebihal" },
        { label: "Pavagada", value: "Pavagada" },
        { label: "Malur", value: "Malur" },
        { label: "Sindhagi", value: "Sindhagi" },
        { label: "Sanduru", value: "Sanduru" },
        { label: "Afzalpur", value: "Afzalpur" },
        { label: "Maddur", value: "Maddur" },
        { label: "Madhugiri", value: "Madhugiri" },
        { label: "Tekkalakote", value: "Tekkalakote" },
        { label: "Terdal", value: "Terdal" },
        { label: "Mudabidri", value: "Mudabidri" },
        { label: "Magadi", value: "Magadi" },
        { label: "Navalgund", value: "Navalgund" },
        { label: "Shiggaon", value: "Shiggaon" },
        { label: "Shrirangapattana", value: "Shrirangapattana" },
        { label: "Sindagi", value: "Sindagi" },
        { label: "Sakaleshapura", value: "Sakaleshapura" },
        { label: "Srinivaspur", value: "Srinivaspur" },
        { label: "Ron", value: "Ron" },
        { label: "Mundargi", value: "Mundargi" },
        { label: "Sadalagi", value: "Sadalagi" },
        { label: "Piriyapatna", value: "Piriyapatna" },
        { label: "Adyar", value: "Adyar" }
      ],
      
    "Manipur":[
        { label: "Imphal", value: "Imphal" },
        { label: "Thoubal", value: "Thoubal" },
        { label: "Lilong", value: "Lilong" },
        { label: "Mayang Imphal", value: "Mayang Imphal" }
      ],  

    "Kerala":[
  { label: "Thiruvananthapuram", value: "Thiruvananthapuram" },
  { label: "Kochi", value: "Kochi" },
  { label: "Kozhikode", value: "Kozhikode" },
  { label: "Kollam", value: "Kollam" },
  { label: "Thrissur", value: "Thrissur" },
  { label: "Palakkad", value: "Palakkad" },
  { label: "Alappuzha", value: "Alappuzha" },
  { label: "Malappuram", value: "Malappuram" },
  { label: "Ponnani", value: "Ponnani" },
  { label: "Vatakara", value: "Vatakara" },
  { label: "Kanhangad", value: "Kanhangad" },
  { label: "Taliparamba", value: "Taliparamba" },
  { label: "Koyilandy", value: "Koyilandy" },
  { label: "Neyyattinkara", value: "Neyyattinkara" },
  { label: "Kayamkulam", value: "Kayamkulam" },
  { label: "Nedumangad", value: "Nedumangad" },
  { label: "Kannur", value: "Kannur" },
  { label: "Tirur", value: "Tirur" },
  { label: "Kottayam", value: "Kottayam" },
  { label: "Kasaragod", value: "Kasaragod" },
  { label: "Kunnamkulam", value: "Kunnamkulam" },
  { label: "Ottappalam", value: "Ottappalam" },
  { label: "Thiruvalla", value: "Thiruvalla" },
  { label: "Thodupuzha", value: "Thodupuzha" },
  { label: "Chalakudy", value: "Chalakudy" },
  { label: "Changanassery", value: "Changanassery" },
  { label: "Punalur", value: "Punalur" },
  { label: "Nilambur", value: "Nilambur" },
  { label: "Cherthala", value: "Cherthala" },
  { label: "Perinthalmanna", value: "Perinthalmanna" },
  { label: "Mattannur", value: "Mattannur" },
  { label: "Shoranur", value: "Shoranur" },
  { label: "Varkala", value: "Varkala" },
  { label: "Paravoor", value: "Paravoor" },
  { label: "Pathanamthitta", value: "Pathanamthitta" },
  { label: "Peringathur", value: "Peringathur" },
  { label: "Attingal", value: "Attingal" },
  { label: "Kodungallur", value: "Kodungallur" },
  { label: "Pappinisseri", value: "Pappinisseri" },
  { label: "Chittur-Thathamangalam", value: "Chittur-Thathamangalam" },
  { label: "Muvattupuzha", value: "Muvattupuzha" },
  { label: "Adoor", value: "Adoor" },
  { label: "Mavelikkara", value: "Mavelikkara" },
  { label: "Mavoor", value: "Mavoor" },
  { label: "Perumbavoor", value: "Perumbavoor" },
  { label: "Vaikom", value: "Vaikom" },
  { label: "Palai", value: "Palai" },
  { label: "Panniyannur", value: "Panniyannur" },
  { label: "Guruvayoor", value: "Guruvayoor" },
  { label: "Puthuppally", value: "Puthuppally" },
  { label: "Panamattom", value: "Panamattom" }
],

    "Delhi":[
        { label: "Delhi", value: "Delhi" },
        { label: "New Delhi", value: "New Delhi" }
      ],
      
    "Dadra and Nagar Haveli": [
        { label: "Silvassa", value: "Silvassa" }
    ],
    "Puducherry":[
        { label: "Pondicherry", value: "Pondicherry" },
        { label: "Karaikal", value: "Karaikal" },
        { label: "Yanam", value: "Yanam" },
        { label: "Mahe", value: "Mahe" }
      ],
      
    "Uttarakhand":[
        { label: "Dehradun", value: "Dehradun" },
        { label: "Hardwar", value: "Hardwar" },
        { label: "Haldwani-cum-Kathgodam", value: "Haldwani-cum-Kathgodam" },
        { label: "Srinagar", value: "Srinagar" },
        { label: "Kashipur", value: "Kashipur" },
        { label: "Roorkee", value: "Roorkee" },
        { label: "Rudrapur", value: "Rudrapur" },
        { label: "Rishikesh", value: "Rishikesh" },
        { label: "Ramnagar", value: "Ramnagar" },
        { label: "Pithoragarh", value: "Pithoragarh" },
        { label: "Manglaur", value: "Manglaur" },
        { label: "Nainital", value: "Nainital" },
        { label: "Mussoorie", value: "Mussoorie" },
        { label: "Tehri", value: "Tehri" },
        { label: "Pauri", value: "Pauri" },
        { label: "Nagla", value: "Nagla" },
        { label: "Sitarganj", value: "Sitarganj" },
        { label: "Bageshwar", value: "Bageshwar" }
      ],
      
    "Uttar Pradesh":[
        { label: "Lucknow", value: "Lucknow" },
        { label: "Kanpur", value: "Kanpur" },
        { label: "Firozabad", value: "Firozabad" },
        { label: "Agra", value: "Agra" },
        { label: "Meerut", value: "Meerut" },
        { label: "Varanasi", value: "Varanasi" },
        { label: "Allahabad", value: "Allahabad" },
        { label: "Amroha", value: "Amroha" },
        { label: "Moradabad", value: "Moradabad" },
        { label: "Aligarh", value: "Aligarh" },
        { label: "Saharanpur", value: "Saharanpur" },
        { label: "Noida", value: "Noida" },
        { label: "Loni", value: "Loni" },
        { label: "Jhansi", value: "Jhansi" },
        { label: "Shahjahanpur", value: "Shahjahanpur" },
        { label: "Rampur", value: "Rampur" },
        { label: "Modinagar", value: "Modinagar" },
        { label: "Hapur", value: "Hapur" },
        { label: "Etawah", value: "Etawah" },
        { label: "Sambhal", value: "Sambhal" },
        { label: "Orai", value: "Orai" },
        { label: "Bahraich", value: "Bahraich" },
        { label: "Unnao", value: "Unnao" },
        { label: "Rae Bareli", value: "Rae Bareli" },
        { label: "Lakhimpur", value: "Lakhimpur" },
        { label: "Sitapur", value: "Sitapur" },
        { label: "Lalitpur", value: "Lalitpur" },
        { label: "Pilibhit", value: "Pilibhit" },
        { label: "Chandausi", value: "Chandausi" },
        { label: "Hardoi", value: "Hardoi" },
        { label: "Azamgarh", value: "Azamgarh" },
        { label: "Khair", value: "Khair" },
        { label: "Sultanpur", value: "Sultanpur" },
        { label: "Tanda", value: "Tanda" },
        { label: "Nagina", value: "Nagina" },
        { label: "Shamli", value: "Shamli" },
        { label: "Najibabad", value: "Najibabad" },
        { label: "Shikohabad", value: "Shikohabad" },
        { label: "Sikandrabad", value: "Sikandrabad" },
        { label: "Shahabad, Hardoi", value: "Shahabad, Hardoi" },
        { label: "Pilkhuwa", value: "Pilkhuwa" },
        { label: "Renukoot", value: "Renukoot" },
        { label: "Vrindavan", value: "Vrindavan" },
        { label: "Ujhani", value: "Ujhani" },
        { label: "Laharpur", value: "Laharpur" },
        { label: "Tilhar", value: "Tilhar" },
        { label: "Sahaswan", value: "Sahaswan" },
        { label: "Rath", value: "Rath" },
        { label: "Sherkot", value: "Sherkot" },
        { label: "Kalpi", value: "Kalpi" },
        { label: "Tundla", value: "Tundla" },
        { label: "Sandila", value: "Sandila" },
        { label: "Nanpara", value: "Nanpara" },
        { label: "Sardhana", value: "Sardhana" },
        { label: "Nehtaur", value: "Nehtaur" },
        { label: "Seohara", value: "Seohara" },
        { label: "Padrauna", value: "Padrauna" },
        { label: "Mathura", value: "Mathura" },
        { label: "Thakurdwara", value: "Thakurdwara" },
        { label: "Nawabganj", value: "Nawabganj" },
        { label: "Siana", value: "Siana" },
        { label: "Noorpur", value: "Noorpur" },
        { label: "Sikandra Rao", value: "Sikandra Rao" },
        { label: "Puranpur", value: "Puranpur" },
        { label: "Rudauli", value: "Rudauli" },
        { label: "Thana Bhawan", value: "Thana Bhawan" },
        { label: "Palia Kalan", value: "Palia Kalan" },
        { label: "Zaidpur", value: "Zaidpur" },
        { label: "Nautanwa", value: "Nautanwa" },
        { label: "Zamania", value: "Zamania" },
        { label: "Shikarpur, Bulandshahr", value: "Shikarpur, Bulandshahr" },
        { label: "Naugawan Sadat", value: "Naugawan Sadat" },
        { label: "Fatehpur Sikri", value: "Fatehpur Sikri" },
        { label: "Shahabad, Rampur", value: "Shahabad, Rampur" },
        { label: "Robertsganj", value: "Robertsganj" },
        { label: "Utraula", value: "Utraula" },
        { label: "Sadabad", value: "Sadabad" },
        { label: "Rasra", value: "Rasra" },
        { label: "Lar", value: "Lar" },
        { label: "Lal Gopalganj Nindaura", value: "Lal Gopalganj Nindaura" },
        { label: "Sirsaganj", value: "Sirsaganj" },
        { label: "Pihani", value: "Pihani" },
        { label: "Shamsabad, Agra", value: "Shamsabad, Agra" },
        { label: "Rudrapur", value: "Rudrapur" },
        { label: "Soron", value: "Soron" },
        { label: "Samdhan", value: "Samdhan" },
        { label: "Sahjanwa", value: "Sahjanwa" },
        { label: "Rampur Maniharan", value: "Rampur Maniharan" },
        { label: "Sumerpur", value: "Sumerpur" },
        { label: "Shahganj", value: "Shahganj" },
        { label: "Tulsipur", value: "Tulsipur" },
        { label: "Tirwaganj", value: "Tirwaganj" },
        { label: "PurqUrban Agglomerationzi", value: "PurqUrban Agglomerationzi" },
        { label: "Shamsabad, Farrukhabad", value: "Shamsabad, Farrukhabad" },
        { label: "Warhapur", value: "Warhapur" },
        { label: "Powayan", value: "Powayan" },
        { label: "Sandi", value: "Sandi" },
        { label: "Achhnera", value: "Achhnera" },
        { label: "Naraura", value: "Naraura" },
        { label: "Nakur", value: "Nakur" },
        { label: "Sahaspur", value: "Sahaspur" },
        { label: "Safipur", value: "Safipur" },
        { label: "Reoti", value: "Reoti" },
        { label: "Sikanderpur", value: "Sikanderpur" },
        { label: "Saidpur", value: "Saidpur" },
        { label: "Sirsi", value: "Sirsi" },
        { label: "Purwa", value: "Purwa" },
        { label: "Parasi", value: "Parasi" },
        { label: "Lalganj", value: "Lalganj" },
        { label: "Phulpur", value: "Phulpur" },
        { label: "Shishgarh", value: "Shishgarh" },
        { label: "Sahawar", value: "Sahawar" },
        { label: "Samthar", value: "Samthar" },
        { label: "Pukhrayan", value: "Pukhrayan" },
        { label: "Obra", value: "Obra" },
        { label: "Niwai", value: "Niwai" },
        { label: "Mirzapur", value: "Mirzapur" }
      ],
      
    "Bihar":[
        { label: "Patna", value: "Patna" },
        { label: "Gaya", value: "Gaya" },
        { label: "Bhagalpur", value: "Bhagalpur" },
        { label: "Muzaffarpur", value: "Muzaffarpur" },
        { label: "Darbhanga", value: "Darbhanga" },
        { label: "Arrah", value: "Arrah" },
        { label: "Begusarai", value: "Begusarai" },
        { label: "Chhapra", value: "Chhapra" },
        { label: "Katihar", value: "Katihar" },
        { label: "Munger", value: "Munger" },
        { label: "Purnia", value: "Purnia" },
        { label: "Saharsa", value: "Saharsa" },
        { label: "Sasaram", value: "Sasaram" },
        { label: "Hajipur", value: "Hajipur" },
        { label: "Dehri-on-Sone", value: "Dehri-on-Sone" },
        { label: "Bettiah", value: "Bettiah" },
        { label: "Motihari", value: "Motihari" },
        { label: "Bagaha", value: "Bagaha" },
        { label: "Siwan", value: "Siwan" },
        { label: "Kishanganj", value: "Kishanganj" },
        { label: "Jamalpur", value: "Jamalpur" },
        { label: "Buxar", value: "Buxar" },
        { label: "Jehanabad", value: "Jehanabad" },
        { label: "Aurangabad", value: "Aurangabad" },
        { label: "Lakhisarai", value: "Lakhisarai" },
        { label: "Nawada", value: "Nawada" },
        { label: "Jamui", value: "Jamui" },
        { label: "Sitamarhi", value: "Sitamarhi" },
        { label: "Araria", value: "Araria" },
        { label: "Gopalganj", value: "Gopalganj" },
        { label: "Madhubani", value: "Madhubani" },
        { label: "Masaurhi", value: "Masaurhi" },
        { label: "Samastipur", value: "Samastipur" },
        { label: "Mokameh", value: "Mokameh" },
        { label: "Supaul", value: "Supaul" },
        { label: "Dumraon", value: "Dumraon" },
        { label: "Arwal", value: "Arwal" },
        { label: "Forbesganj", value: "Forbesganj" },
        { label: "BhabUrban Agglomeration", value: "BhabUrban Agglomeration" },
        { label: "Narkatiaganj", value: "Narkatiaganj" },
        { label: "Naugachhia", value: "Naugachhia" },
        { label: "Madhepura", value: "Madhepura" },
        { label: "Sheikhpura", value: "Sheikhpura" },
        { label: "Sultanganj", value: "Sultanganj" },
        { label: "Raxaul Bazar", value: "Raxaul Bazar" },
        { label: "Ramnagar", value: "Ramnagar" },
        { label: "Mahnar Bazar", value: "Mahnar Bazar" },
        { label: "Warisaliganj", value: "Warisaliganj" },
        { label: "Revelganj", value: "Revelganj" },
        { label: "Rajgir", value: "Rajgir" },
        { label: "Sonepur", value: "Sonepur" },
        { label: "Sherghati", value: "Sherghati" },
        { label: "Sugauli", value: "Sugauli" },
        { label: "Makhdumpur", value: "Makhdumpur" },
        { label: "Maner", value: "Maner" },
        { label: "Rosera", value: "Rosera" },
        { label: "Nokha", value: "Nokha" },
        { label: "Piro", value: "Piro" },
        { label: "Rafiganj", value: "Rafiganj" },
        { label: "Marhaura", value: "Marhaura" },
        { label: "Mirganj", value: "Mirganj" },
        { label: "Lalganj", value: "Lalganj" },
        { label: "Murliganj", value: "Murliganj" },
        { label: "Motipur", value: "Motipur" },
        { label: "Manihari", value: "Manihari" },
        { label: "Sheohar", value: "Sheohar" },
        { label: "Maharajganj", value: "Maharajganj" },
        { label: "Silao", value: "Silao" },
        { label: "Barh", value: "Barh" },
        { label: "Asarganj", value: "Asarganj" }
      ],
      
    "Gujarat":[
        { label: "Ahmedabad", value: "Ahmedabad" },
        { label: "Surat", value: "Surat" },
        { label: "Vadodara", value: "Vadodara" },
        { label: "Rajkot", value: "Rajkot" },
        { label: "Bhavnagar", value: "Bhavnagar" },
        { label: "Jamnagar", value: "Jamnagar" },
        { label: "Nadiad", value: "Nadiad" },
        { label: "Porbandar", value: "Porbandar" },
        { label: "Anand", value: "Anand" },
        { label: "Morvi", value: "Morvi" },
        { label: "Mahesana", value: "Mahesana" },
        { label: "Bharuch", value: "Bharuch" },
        { label: "Vapi", value: "Vapi" },
        { label: "Navsari", value: "Navsari" },
        { label: "Veraval", value: "Veraval" },
        { label: "Bhuj", value: "Bhuj" },
        { label: "Godhra", value: "Godhra" },
        { label: "Palanpur", value: "Palanpur" },
        { label: "Valsad", value: "Valsad" },
        { label: "Patan", value: "Patan" },
        { label: "Deesa", value: "Deesa" },
        { label: "Amreli", value: "Amreli" },
        { label: "Anjar", value: "Anjar" },
        { label: "Dhoraji", value: "Dhoraji" },
        { label: "Khambhat", value: "Khambhat" },
        { label: "Mahuva", value: "Mahuva" },
        { label: "Keshod", value: "Keshod" },
        { label: "Wadhwan", value: "Wadhwan" },
        { label: "Ankleshwar", value: "Ankleshwar" },
        { label: "Savarkundla", value: "Savarkundla" },
        { label: "Kadi", value: "Kadi" },
        { label: "Visnagar", value: "Visnagar" },
        { label: "Upleta", value: "Upleta" },
        { label: "Una", value: "Una" },
        { label: "Sidhpur", value: "Sidhpur" },
        { label: "Unjha", value: "Unjha" },
        { label: "Mangrol", value: "Mangrol" },
        { label: "Viramgam", value: "Viramgam" },
        { label: "Modasa", value: "Modasa" },
        { label: "Palitana", value: "Palitana" },
        { label: "Petlad", value: "Petlad" },
        { label: "Kapadvanj", value: "Kapadvanj" },
        { label: "Sihor", value: "Sihor" },
        { label: "Wankaner", value: "Wankaner" },
        { label: "Limbdi", value: "Limbdi" },
        { label: "Mandvi", value: "Mandvi" },
        { label: "Thangadh", value: "Thangadh" },
        { label: "Vyara", value: "Vyara" },
        { label: "Padra", value: "Padra" },
        { label: "Lunawada", value: "Lunawada" },
        { label: "Rajpipla", value: "Rajpipla" },
        { label: "Vapi", value: "Vapi" },
        { label: "Umreth", value: "Umreth" },
        { label: "Sanand", value: "Sanand" },
        { label: "Rajula", value: "Rajula" },
        { label: "Radhanpur", value: "Radhanpur" },
        { label: "Mahemdabad", value: "Mahemdabad" },
        { label: "Ranavav", value: "Ranavav" },
        { label: "Tharad", value: "Tharad" },
        { label: "Mansa", value: "Mansa" },
        { label: "Umbergaon", value: "Umbergaon" },
        { label: "Talaja", value: "Talaja" },
        { label: "Vadnagar", value: "Vadnagar" },
        { label: "Manavadar", value: "Manavadar" },
        { label: "Salaya", value: "Salaya" },
        { label: "Vijapur", value: "Vijapur" },
        { label: "Pardi", value: "Pardi" },
        { label: "Rapar", value: "Rapar" },
        { label: "Songadh", value: "Songadh" },
        { label: "Lathi", value: "Lathi" },
        { label: "Adalaj", value: "Adalaj" },
        { label: "Chhapra", value: "Chhapra" },
        { label: "Gandhinagar", value: "Gandhinagar" }
      ],
      
    "Telangana":[
        { label: "Hyderabad", value: "Hyderabad" },
        { label: "Warangal", value: "Warangal" },
        { label: "Nizamabad", value: "Nizamabad" },
        { label: "Karimnagar", value: "Karimnagar" },
        { label: "Ramagundam", value: "Ramagundam" },
        { label: "Khammam", value: "Khammam" },
        { label: "Mahbubnagar", value: "Mahbubnagar" },
        { label: "Mancherial", value: "Mancherial" },
        { label: "Adilabad", value: "Adilabad" },
        { label: "Suryapet", value: "Suryapet" },
        { label: "Jagtial", value: "Jagtial" },
        { label: "Miryalaguda", value: "Miryalaguda" },
        { label: "Nirmal", value: "Nirmal" },
        { label: "Kamareddy", value: "Kamareddy" },
        { label: "Kothagudem", value: "Kothagudem" },
        { label: "Bodhan", value: "Bodhan" },
        { label: "Palwancha", value: "Palwancha" },
        { label: "Mandamarri", value: "Mandamarri" },
        { label: "Koratla", value: "Koratla" },
        { label: "Sircilla", value: "Sircilla" },
        { label: "Tandur", value: "Tandur" },
        { label: "Siddipet", value: "Siddipet" },
        { label: "Wanaparthy", value: "Wanaparthy" },
        { label: "Kagaznagar", value: "Kagaznagar" },
        { label: "Gadwal", value: "Gadwal" },
        { label: "Sangareddy", value: "Sangareddy" },
        { label: "Bellampalle", value: "Bellampalle" },
        { label: "Bhongir", value: "Bhongir" },
        { label: "Vikarabad", value: "Vikarabad" },
        { label: "Jangaon", value: "Jangaon" },
        { label: "Bhadrachalam", value: "Bhadrachalam" },
        { label: "Bhainsa", value: "Bhainsa" },
        { label: "Farooqnagar", value: "Farooqnagar" },
        { label: "Medak", value: "Medak" },
        { label: "Narayanpet", value: "Narayanpet" },
        { label: "Sadasivpet", value: "Sadasivpet" },
        { label: "Yellandu", value: "Yellandu" },
        { label: "Manuguru", value: "Manuguru" },
        { label: "Kyathampalle", value: "Kyathampalle" },
        { label: "Nagarkurnool", value: "Nagarkurnool" }
      ],
      
    "Meghalaya": [
        { label: "Shillong", value: "Shillong" },
        { label: "Tura", value: "Tura" },
        { label: "Nongstoin", value: "Nongstoin" }
    ],
    "Himachal Praddesh": [
        { label: "Manali", value: "Manali" }
    ],
    "Arunachal Pradesh": [
        { label: "Naharlagun", value: "Naharlagun" },
        { label: "Pasighat", value: "Pasighat" }
    ],
    "Maharashtra":[
        { label: "Mumbai", value: "Mumbai" },
        { label: "Pune", value: "Pune" },
        { label: "Nagpur", value: "Nagpur" },
        { label: "Thane", value: "Thane" },
        { label: "Nashik", value: "Nashik" },
        { label: "Kalyan-Dombivali", value: "Kalyan-Dombivali" },
        { label: "Vasai-Virar", value: "Vasai-Virar" },
        { label: "Solapur", value: "Solapur" },
        { label: "Mira-Bhayandar", value: "Mira-Bhayandar" },
        { label: "Bhiwandi", value: "Bhiwandi" },
        { label: "Amravati", value: "Amravati" },
        { label: "Nanded-Waghala", value: "Nanded-Waghala" },
        { label: "Sangli", value: "Sangli" },
        { label: "Malegaon", value: "Malegaon" },
        { label: "Akola", value: "Akola" },
        { label: "Latur", value: "Latur" },
        { label: "Dhule", value: "Dhule" },
        { label: "Ahmednagar", value: "Ahmednagar" },
        { label: "Ichalkaranji", value: "Ichalkaranji" },
        { label: "Parbhani", value: "Parbhani" },
        { label: "Panvel", value: "Panvel" },
        { label: "Yavatmal", value: "Yavatmal" },
        { label: "Achalpur", value: "Achalpur" },
        { label: "Osmanabad", value: "Osmanabad" },
        { label: "Nandurbar", value: "Nandurbar" },
        { label: "Satara", value: "Satara" },
        { label: "Wardha", value: "Wardha" },
        { label: "Udgir", value: "Udgir" },
        { label: "Aurangabad", value: "Aurangabad" },
        { label: "Amalner", value: "Amalner" },
        { label: "Akot", value: "Akot" },
        { label: "Pandharpur", value: "Pandharpur" },
        { label: "Shrirampur", value: "Shrirampur" },
        { label: "Parli", value: "Parli" },
        { label: "Washim", value: "Washim" },
        { label: "Ambejogai", value: "Ambejogai" },
        { label: "Manmad", value: "Manmad" },
        { label: "Ratnagiri", value: "Ratnagiri" },
        { label: "Uran Islampur", value: "Uran Islampur" },
        { label: "Pusad", value: "Pusad" },
        { label: "Sangamner", value: "Sangamner" },
        { label: "Shirpur-Warwade", value: "Shirpur-Warwade" },
        { label: "Malkapur", value: "Malkapur" },
        { label: "Wani", value: "Wani" },
        { label: "Lonavla", value: "Lonavla" },
        { label: "Talegaon Dabhade", value: "Talegaon Dabhade" },
        { label: "Anjangaon", value: "Anjangaon" },
        { label: "Umred", value: "Umred" },
        { label: "Palghar", value: "Palghar" },
        { label: "Shegaon", value: "Shegaon" },
        { label: "Ozar", value: "Ozar" },
        { label: "Phaltan", value: "Phaltan" },
        { label: "Yevla", value: "Yevla" },
        { label: "Shahade", value: "Shahade" },
        { label: "Vita", value: "Vita" },
        { label: "Umarkhed", value: "Umarkhed" },
        { label: "Warora", value: "Warora" },
        { label: "Pachora", value: "Pachora" },
        { label: "Tumsar", value: "Tumsar" },
        { label: "Manjlegaon", value: "Manjlegaon" },
        { label: "Sillod", value: "Sillod" },
        { label: "Arvi", value: "Arvi" },
        { label: "Nandura", value: "Nandura" },
        { label: "Vaijapur", value: "Vaijapur" },
        { label: "Wadgaon Road", value: "Wadgaon Road" },
        { label: "Sailu", value: "Sailu" },
        { label: "Murtijapur", value: "Murtijapur" },
        { label: "Tasgaon", value: "Tasgaon" },
        { label: "Mehkar", value: "Mehkar" },
        { label: "Yawal", value: "Yawal" },
        { label: "Pulgaon", value: "Pulgaon" },
        { label: "Nilanga", value: "Nilanga" },
        { label: "Wai", value: "Wai" },
        { label: "Umarga", value: "Umarga" },
        { label: "Paithan", value: "Paithan" },
        { label: "Rahuri", value: "Rahuri" },
        { label: "Nawapur", value: "Nawapur" },
        { label: "Tuljapur", value: "Tuljapur" },
        { label: "Morshi", value: "Morshi" },
        { label: "Purna", value: "Purna" },
        { label: "Satana", value: "Satana" },
        { label: "Pathri", value: "Pathri" },
        { label: "Sinnar", value: "Sinnar" },
        { label: "Uchgaon", value: "Uchgaon" },
        { label: "Uran", value: "Uran" },
        { label: "Pen", value: "Pen" },
        { label: "Karjat", value: "Karjat" },
        { label: "Manwath", value: "Manwath" },
        { label: "Partur", value: "Partur" },
        { label: "Sangole", value: "Sangole" },
        { label: "Mangrulpir", value: "Mangrulpir" },
        { label: "Risod", value: "Risod" },
        { label: "Shirur", value: "Shirur" },
        { label: "Savner", value: "Savner" },
        { label: "Sasvad", value: "Sasvad" },
        { label: "Pandharkaoda", value: "Pandharkaoda" },
        { label: "Talode", value: "Talode" },
        { label: "Shrigonda", value: "Shrigonda" },
        { label: "Shirdi", value: "Shirdi" },
        { label: "Raver", value: "Raver" },
        { label: "Mukhed", value: "Mukhed" },
        { label: "Rajura", value: "Rajura" },
        { label: "Vadgaon Kasba", value: "Vadgaon Kasba" },
        { label: "Tirora", value: "Tirora" },
        { label: "Mahad", value: "Mahad" },
        { label: "Lonar", value: "Lonar" },
        { label: "Sawantwadi", value: "Sawantwadi" },
        { label: "Pathardi", value: "Pathardi" },
        { label: "Pauni", value: "Pauni" },
        { label: "Ramtek", value: "Ramtek" },
        { label: "Mul", value: "Mul" },
        { label: "Soyagaon", value: "Soyagaon" },
        { label: "Mangalvedhe", value: "Mangalvedhe" },
        { label: "Narkhed", value: "Narkhed" },
        { label: "Shendurjana", value: "Shendurjana" },
        { label: "Patur", value: "Patur" },
        { label: "Mhaswad", value: "Mhaswad" },
        { label: "Loha", value: "Loha" },
        { label: "Nandgaon", value: "Nandgaon" },
        { label: "Warud", value: "Warud" }
      ],
    "Goa": [
        { label: "Marmagao", value: "Marmagao" },
        { label: "Panaji", value: "Panaji" },
        { label: "Margao", value: "Margao" },
        { label: "Mapusa", value: "Mapusa" }
    ],
    "West Bengal":[
        { label: "Kolkata", value: "Kolkata" },
        { label: "Siliguri", value: "Siliguri" },
        { label: "Asansol", value: "Asansol" },
        { label: "Raghunathganj", value: "Raghunathganj" },
        { label: "Kharagpur", value: "Kharagpur" },
        { label: "Naihati", value: "Naihati" },
        { label: "English Bazar", value: "English Bazar" },
        { label: "Baharampur", value: "Baharampur" },
        { label: "Hugli-Chinsurah", value: "Hugli-Chinsurah" },
        { label: "Raiganj", value: "Raiganj" },
        { label: "Jalpaiguri", value: "Jalpaiguri" },
        { label: "Santipur", value: "Santipur" },
        { label: "Balurghat", value: "Balurghat" },
        { label: "Medinipur", value: "Medinipur" },
        { label: "Habra", value: "Habra" },
        { label: "Ranaghat", value: "Ranaghat" },
        { label: "Bankura", value: "Bankura" },
        { label: "Nabadwip", value: "Nabadwip" },
        { label: "Darjiling", value: "Darjiling" },
        { label: "Purulia", value: "Purulia" },
        { label: "Arambagh", value: "Arambagh" },
        { label: "Tamluk", value: "Tamluk" },
        { label: "AlipurdUrban Agglomerationr", value: "AlipurdUrban Agglomerationr" },
        { label: "Suri", value: "Suri" },
        { label: "Jhargram", value: "Jhargram" },
        { label: "Gangarampur", value: "Gangarampur" },
        { label: "Rampurhat", value: "Rampurhat" },
        { label: "Kalimpong", value: "Kalimpong" },
        { label: "Sainthia", value: "Sainthia" },
        { label: "Taki", value: "Taki" },
        { label: "Murshidabad", value: "Murshidabad" },
        { label: "Memari", value: "Memari" },
        { label: "Paschim Punropara", value: "Paschim Punropara" },
        { label: "Tarakeswar", value: "Tarakeswar" },
        { label: "Sonamukhi", value: "Sonamukhi" },
        { label: "PandUrban Agglomeration", value: "PandUrban Agglomeration" },
        { label: "Mainaguri", value: "Mainaguri" },
        { label: "Malda", value: "Malda" },
        { label: "Panchla", value: "Panchla" },
        { label: "Raghunathpur", value: "Raghunathpur" },
        { label: "Mathabhanga", value: "Mathabhanga" },
        { label: "Monoharpur", value: "Monoharpur" },
        { label: "Srirampore", value: "Srirampore" },
        { label: "Adra", value: "Adra" }
      ]
      
  }
] 




  