import { all, fork } from 'redux-saga/effects';
import { watchFollowUpDataSaga } from './collection/followUp';
import { watchNoticesSaga } from './collection/notices';
import { watchCollectionSaga } from './collection/paymentCollection';
import { login, logout, updatePassword } from './auth';
import { watchCollectionDashboardSaga } from './collection/collectionDashboard';
import {
  watchCaseCollectionSaga,
  watchCreateCaseRemark,
  watchdeleteRemarkSaga,
  watchUnassignCaseSaga,
  watchUserAssignCaseSaga,
  watchFetchCasesaga,
  watchFetchCollectionViewSaga,
  watchFetchFollowUpByView,
  watchFetchCollectionSaga,
  watchEXportCaseSaga,
  watchUpdateBranchSaga,
  watchUpdateCaseContactNoSaga,
  watchUploadCollectionSaga,
  watchCollectionDashboardReportsSaga,
  watchFlagCaseSaga,
} from './collection';
import {
  blockEmployees,
  editEmployee,
  fetchEmployeeById,
  fetchEmployees,
  registerNewEmployees,
  unblockEmployee,
} from './employees';
import {
  getCustomerFileById,
  HandleFileComments,
  HandleFilePayment,
  HandleFileStatus,
  resetAllStepsStates,
  FileIFSC,
  verifyFormStep,
  getCustomerFile,
  getCustomerFileSilent,
  OCRData,
  verifyTelephoneQuestionStep,
  Dashboard,
} from './files/main';
import { addCustomerAddress, getCustomerAddress, editCustomerAddress } from './files/address';
import { addCustomerAssociates, fetchCustomerAssociates, editCustomerAssociates } from './files/associates';
import { updateCibilScore } from './files/backOffice';
import { addCustomerBank, editCustomerBank, getCustomerBank } from './files/bank';
import { addCustomerCollateral, editCustomerCollateral, getCustomerCollateral } from './files/collateral';
import { addCustomerDetails, editCustomerDetails, getCustomerDetails } from './files/customer';
import { addCustomerIncome, editCustomerIncome, getCustomerIncome } from './files/income';
import {
  addCustomerLiability,
  addExistingLoan,
  editCustomerLiability,
  editExistingLoan,
  getCustomerLiability,
} from './files/liability';
import { addCustomerPhoto, deletePhoto, editCustomerPhoto, getCustomerPhotos } from './files/photos';
import {
  registerPendency,
  editPendency,
  fetchPendency,
  markPendencyAsCompleted,
  reactivePendency,
} from './pendency/index';
import { editRole, fetchPermissions, fetchRoles, registerNewRole, deleteRolesSaga } from './roles';
import {
  deleteTasks,
  deleteScheduledRecurringTasks,
  editTask,
  updateScheduledRecurringTask,
  fetchTasks,
  fetchScheduledRecurringTasks,
  fileHandlers,
  markAsDone,
  createTaskSaga,
  stopTaskRepeat,
  taskComment,
  acceptTask,
  pinTask,
} from './tasks';

import { deleteQuestion, editQuestion, fetchQuestions, registerNewQuestion } from './televerification';
import {
  blockUser,
  editUser,
  fetchUserData,
  fetchUserDataById,
  fetchUsersDetails,
  recieveUserLedger,
  registerUser,
  unblockUser,
} from './users';
import {
  watchBlockBranches,
  watchDeleteBranchSaga,
  watchEditBranches,
  watchFetchBranchesData,
  watchFetchBranchesDataById,
  watchUnlockBranches,
} from './branches';
import fetchBranchesById from './branches/fetchBranchById.saga';
import registerNewBranch from './branches/registerNewBranch.saga';
import {
  getFamilyDetailsSaga,
  getPersonalDetailsSaga,
  getPropertyDetailsSaga,
  updateFamilyDetailsSaga,
  updatePersonalDetailsSaga,
  updatePropertyDetailsSaga,
  addIncomeDetailsSaga,
  deleteIncomeDetailsSaga,
  editIncomeDetailsSaga,
  getIncomeDetailsSaga,
  getCreditLiabilitySaga,
  addCreditLiabilitySaga,
  deleteCreditLiabilitySaga,
} from './credit';
import {
  deleteOrganization,
  editOrganization,
  fetchOrganization,
  fetchOrganizationByIdData,
  registerNewOrganization,
} from './organizationAdmin';
import { createLoanSaga, watchFetchLoans, fetchAllLoansStatistics, watchFetchLoanById } from './loanManagement';

import { addService, deleteService, editService, getServices, fetchServicesById } from './tasks/service';
import { addClient, deleteClient, editClient, getClients, getClientById } from './tasks/client';
import { addDepartment, deleteDepartment, editDepartment, getDepartments } from './tasks/department';
import { fetchOrganizationConfigs } from './organizationConfigs';
import fetchTasksDashboard from './tasks/fetchDashboard.saga';
export default function* rootSaga() {
  const sagas = [
    fetchServicesById,
    addService,
    addDepartment,
    deleteDepartment,
    editDepartment,
    getDepartments,
    deleteService,
    editService,
    getServices,
    addClient,
    deleteClient,
    editClient,
    getClients,
    getClientById,
    addCreditLiabilitySaga,
    deleteCreditLiabilitySaga,
    getFamilyDetailsSaga,
    getPersonalDetailsSaga,
    getPropertyDetailsSaga,
    updateFamilyDetailsSaga,
    updatePersonalDetailsSaga,
    updatePropertyDetailsSaga,
    login,
    logout,
    deleteQuestion,
    editQuestion,
    fetchQuestions,
    registerNewQuestion,
    updatePassword,
    watchCollectionDashboardSaga,
    watchCollectionDashboardReportsSaga,
    fetchUserData,
    fetchUserDataById,
    registerUser,
    blockUser,
    unblockUser,
    editUser,
    recieveUserLedger,
    watchBlockBranches,
    watchEditBranches,
    watchFetchBranchesData,
    watchFetchBranchesDataById,
    registerNewBranch,
    watchUnlockBranches,
    blockEmployees,
    editEmployee,
    fetchEmployeeById,
    fetchEmployees,
    registerNewEmployees,
    unblockEmployee,
    getCustomerFileById,
    HandleFileComments,
    HandleFilePayment,
    HandleFileStatus,
    resetAllStepsStates,
    FileIFSC,
    verifyFormStep,
    getCustomerFile,
    getCustomerFileSilent,
    OCRData,
    verifyTelephoneQuestionStep,
    Dashboard,
    deleteTasks,
    deleteScheduledRecurringTasks,
    editTask,
    updateScheduledRecurringTask,
    fetchTasks,
    fetchScheduledRecurringTasks,
    fileHandlers,
    markAsDone,
    createTaskSaga,
    stopTaskRepeat,
    taskComment,
    acceptTask,
    fetchTasksDashboard,
    registerPendency,
    editPendency,
    fetchPendency,
    markPendencyAsCompleted,
    reactivePendency,
    fetchBranchesById,
    addCustomerDetails,
    editCustomerDetails,
    getCustomerDetails,
    addCustomerAddress,
    getCustomerAddress,
    editCustomerAddress,
    addCustomerAssociates,
    fetchCustomerAssociates,
    editCustomerAssociates,
    addCustomerBank,
    editCustomerBank,
    getCustomerBank,
    addCustomerCollateral,
    editCustomerCollateral,
    getCustomerCollateral,
    addCustomerIncome,
    editCustomerIncome,
    getCustomerIncome,
    addCustomerLiability,
    addExistingLoan,
    editCustomerLiability,
    editExistingLoan,
    getCustomerLiability,
    addCustomerPhoto,
    deletePhoto,
    editCustomerPhoto,
    getCustomerPhotos,
    watchNoticesSaga,
    watchCollectionSaga,
    watchFollowUpDataSaga,
    updateCibilScore,
    editRole,
    fetchPermissions,
    fetchRoles,
    registerNewRole,
    deleteRolesSaga,
    // watchCibilScoreUpdate,
    // watchRolesSaga,
    watchDeleteBranchSaga,
    watchCaseCollectionSaga,
    watchCreateCaseRemark,
    watchdeleteRemarkSaga,
    watchUnassignCaseSaga,
    watchUserAssignCaseSaga,
    watchFetchCasesaga,
    watchFetchCollectionSaga,
    watchFetchCollectionViewSaga,
    watchFetchFollowUpByView,
    watchEXportCaseSaga,
    watchUpdateBranchSaga,
    watchUpdateCaseContactNoSaga,
    watchUploadCollectionSaga,
    addIncomeDetailsSaga,
    deleteIncomeDetailsSaga,
    editIncomeDetailsSaga,
    getIncomeDetailsSaga,
    getCreditLiabilitySaga,
    registerNewOrganization,
    fetchOrganization,
    editOrganization,
    deleteOrganization,
    fetchOrganizationByIdData,
    fetchUsersDetails,
    watchFlagCaseSaga,
    pinTask,
    createLoanSaga,
    watchFetchLoans,
    fetchAllLoansStatistics,
    watchFetchLoanById,
    fetchOrganizationConfigs,
  ];

  yield all(sagas.map((saga) => fork(saga)));
}
